# This is the app definition for running in test.
# It runs a Postgres container and sets the web app to use Postgres.
# It also sets the containers to restart, and uses a bind mount for the database files.
services:
  todo-db:
    image: diamol/postgres:2e-12
    restart: unless-stopped
    environment:
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - type: bind
        source: /tmp/data/postgres
        target: /var/lib/postgresql/data
    networks:
      - app-net

  todo-web:
    image: diamol/ch06-todo-list:2e
    restart: unless-stopped
    ports:
      - "8050:8080"
    environment:
      - Database:Provider=Postgres
    networks:
      - app-net
    depends_on:
      - todo-db
    secrets:
      - source: postgres-connection
        target: /app/config/secrets.json

secrets:
  postgres-connection:
    file: postgres-connection.json

networks:
  app-net:
    name: nat
    external: true
      
