# This is the app definition for running in dev.
# It uses a Sqlite database inside the web app container.
services:
  todo-web:
    image: diamol/ch06-todo-list:2e
    ports:
      - "8020:8080"
    environment:
      - Database:Provider=Sqlite
    networks:
      - app-net

networks:
  app-net:
    name: nat
    external: true
      
