services:
  gogs:
    image: diamol/gogs:2e
    ports:
      - "3000:3000"
    networks:
      - infrastructure

  registry.local:
    image: diamol/registry:2e
    ports:
      - "5010:5000"
    networks:
      - infrastructure

  jenkins:
    image: diamol/jenkins:2e
    ports:
      - "8080:8080"
    networks:
      - infrastructure

networks:
  infrastructure:
    name: build-infrastructure
